---
# tasks file for roles/database
# Description: This file contains the tasks to deploy the frontend on the target servers.
- name: Run frontend
  vars:
    ansible_python_interpreter: /usr/bin/python3
  docker_container:
    name: frontend
    image: noreddinelam/tp-devops-frontend:latest
    networks:
      - name: app-network
    ports:
      - "9000:80"

