---
# tasks file for roles/database
# Description: This file contains the tasks to deploy the database on the target servers.
- name: Run database
  vars:
    ansible_python_interpreter: /usr/bin/python3
  docker_container:
    name: database
    image: noreddinelam/tp-devops-database:latest
    networks:
      - name: app-network
    ports:
      - "5432:5432"

