version: '3.7'

services:
    backend:
        build:
          context: ./simpleapi/
          dockerfile: ./Dockerfile
        environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
        container_name: backendapi
        ports:
        - "8080:8080"
        networks:
        - app-network
        depends_on:
        - database

    database:
        build:
          context: .
          dockerfile: ./DatabaseDockerFile
        ports:
        - "5432:5432"
        networks:
        - app-network

    httpd:
        build:
          context: ./http-server/
          dockerfile: ./Dockerfile
        ports:
        - "7000:80"
        networks:
        - app-network
        depends_on:
        - backend

networks:
    app-network:
      driver: bridge
