---
# tasks file for roles/network
# Description: This file contains the tasks to create a Docker network on the target servers.
- name: Create a Docker network
  docker_network:
    name: app-network
    driver: bridge
    state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
