---
# Description: Install Docker
- name: Install python3
  yum:
    name: python3
    state: present

- name: Install device-mapper-persistent-data
  yum:
    name: device-mapper-persistent-data
    state: latest

- name: Install lvm2
  yum:
    name: lvm2
    state: latest

- name: add repo docker
  command:
    cmd: sudo yum-config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo

- name: Install Docker
  yum:
    name: docker-ce
    state: present

- name: Install docker with Python 3
  pip:
    name: docker
    executable: pip3
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Make sure Docker is running
  service: name=docker state=started
  tags: docker

- name: Log in to Docker registry
  docker_login:
    registry_url: "https://index.docker.io/v1/"
    username: "{{ lookup('env', 'DOCKER_USERNAME') }}"
    password: "{{ lookup('env', 'DOCKER_PASSWORD') }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3
