---
# tasks file for roles/proxy
- name: Run ReverseProxy
  vars:
    ansible_python_interpreter: /usr/bin/python3
  docker_container:
    name: httpd
    image: noreddinelam/tp-devops-http-server:latest
    networks:
      - name: app-network
    ports:
      - "80:80"

