name: CD devops 2024 # This is the second workflow that will be executed and it aims to push the images to DockerHub
on: # Launch this job when the first workflow is completed and the code is pushed to main
  workflow_run:
    workflows: [ "CI devops 2024" ]
    types:
      - completed
    branches:
      - main
jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub registry # Log in to DockerHub
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build image and push backend # Build the image and push it to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./simpleapi
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tp-devops-simple-api:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push database # Build the image and push it to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./database
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tp-devops-database:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push httpd # Build the image and push it to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./http-server
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tp-devops-http-server:latest
          push: ${{ github.ref == 'refs/heads/main' }}

      - name: Build image and push frontend # Build the image and push it to DockerHub
        uses: docker/build-push-action@v3
        with:
          context: ./frontend
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/tp-devops-frontend:latest
          push: ${{ github.ref == 'refs/heads/main' }}
