name: CD - Ansible devops 2024 # This is the third workflow that will be executed and it aims to deploy the application with Ansible
on: # Launch this job when the second workflow is completed and the code is pushed to main
  workflow_run:
    workflows: [ "CD devops 2024" ]
    types:
      - completed
    branches:
      - main
jobs:
  push-app-with-ansible:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible

      - name: Make sure Ansible is installed
        run: ansible --version

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H noreddinelamamra.takima.cloud >> ~/.ssh/known_hosts

      - name: Run Ansible playbook # Run the Ansible playbook to deploy the application
        env: # Define the environment variables to be used in the playbook inside the job
          ANSIBLE_HOST_KEY_CHECKING: False
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        shell: bash
        run: |
          ansible-playbook -vvv -i ansible/inventories/setup.yml ansible/deploy-app.yml
